

export const GET_RESTAURANT_FOOD_SUCCESS = "GET_RESTAURANT_FOOD_SUCCESS";
export const GET_RESTAURANT_FOOD_FAILURE = "GET_RESTAURANT_FOOD_FAILURE";
export const GET_RESTAURANT_FOOD_REQUEST = "GET_RESTAURANT_FOOD_REQUEST";

export const GET_INGREDIENT_REQUEST = "GET_INGREDIENT_REQUEST";
export const GET_INGREDIENT_SUCCESS = "GET_INGREDIENT_SUCCESS";
export const GET_INGREDIENT_FAILURE = "GET_INGREDIENT_FAILURE";

export const GET_CATEGORY_RESTAURANT_SUCCESS = "GET_CATEGORY_RESTAURANT_SUCCESS";
export const GET_CATEGORY_RESTAURANT_FAILURE = "GET_CATEGORY_RESTAURANT_FAILURE";
export const GET_CATEGORY_RESTAURANT_REQUEST = "GET_CATEGORY_RESTAURANT_REQUEST";